export const initialCategories = [
  {
    id: 1,
    name: 'Audio',
    slug: 'audio',
    description: 'High-quality headphones, earbuds, speakers, and audio gear.',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=1200&auto=format&fit=crop',
    iconName: 'Headphones',
    isActive: true,
  },
  {
    id: 2,
    name: 'Wearables',
    slug: 'wearables',
    description: 'Smart watches, fitness bands, and wearable technology.',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=1200&auto=format&fit=crop',
    iconName: 'Watch',
    isActive: true,
  },
  {
    id: 3,
    name: 'Cameras',
    slug: 'cameras',
    description: 'Professional cameras, webcams, lenses, and photography equipment.',
    image: 'https://images.unsplash.com/photo-1612198188060-c7c2a3b66eae?q=80&w=1200&auto=format&fit=crop',
    iconName: 'Camera',
    isActive: true,
  },
  {
    id: 4,
    name: 'Accessories',
    slug: 'accessories',
    description: 'Everyday gadgets, stands, tripods, hubs, and connectors.',
    image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?q=80&w=1200&auto=format&fit=crop',
    iconName: 'Sparkles',
    isActive: true,
  },
  {
    id: 5,
    name: 'Office & Desk',
    slug: 'office-desk',
    description: 'Keyboards, mice, desk lamps, and workspaces organization.',
    image: 'https://images.unsplash.com/photo-1587829191301-dc798b83add3?q=80&w=1200&auto=format&fit=crop',
    iconName: 'Keyboard',
    isActive: true,
  },
  {
    id: 6,
    name: 'Mobile Accessories',
    slug: 'mobile-accessories',
    description: 'Cases, screen protectors, and chargers for your smartphones.',
    image: 'https://images.unsplash.com/photo-1606933248051-5ce42bebce85?q=80&w=1200&auto=format&fit=crop',
    iconName: 'Smartphone',
    isActive: true,
  },
  {
    id: 7,
    name: 'Home Appliances',
    slug: 'home-appliances',
    description: 'Smart home automation, appliances, and accessories.',
    image: 'https://images.unsplash.com/photo-1565636192335-14c01e2335d6?q=80&w=1200&auto=format&fit=crop',
    iconName: 'Home',
    isActive: true,
  },
  {
    id: 8,
    name: 'Gadgets',
    slug: 'gadgets',
    description: 'Smart gadgets, tools, and tech novelties.',
    image: 'https://images.unsplash.com/photo-1625948515291-69613efd103f?q=80&w=1200&auto=format&fit=crop',
    iconName: 'Cpu',
    isActive: true,
  },
];

export const initialProducts = [
  // Today's Deals (1 - 8)
  {
    id: 1,
    name: 'Premium Wireless Headphones',
    slug: 'premium-wireless-headphones',
    description: 'Experience studio-quality audio with active noise cancellation and 40-hour battery life.',
    price: 129.99,
    discount: 25.0,
    brand: 'AudioTech',
    category: 'Audio',
    sku: 'AUDIO-HEAD-01',
    stockQty: 50,
    weight: 0.3,
    thumbnail: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=1200&auto=format&fit=crop',
    rating: 4.8,
    reviews: 324,
    isBestseller: true,
    isNew: true,
    isDealOfDay: true,
    isActive: true,
  },
  {
    id: 2,
    name: 'Smart Watch Pro',
    slug: 'smart-watch-pro',
    description: 'Stay connected and track your vitals with cellular connectivity and water resistance up to 50m.',
    price: 199.99,
    discount: 33.0,
    brand: 'WearTech',
    category: 'Wearables',
    sku: 'WEAR-SW-02',
    stockQty: 30,
    weight: 0.1,
    thumbnail: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=1200&auto=format&fit=crop',
    rating: 4.6,
    reviews: 156,
    isBestseller: false,
    isNew: true,
    isDealOfDay: true,
    isActive: true,
  },
  {
    id: 3,
    name: 'Ultra HD Camera',
    slug: 'ultra-hd-camera',
    description: 'Capture stunning landscapes and details with 4K video capabilities and continuous autofocus.',
    price: 799.99,
    discount: 20.0,
    brand: 'CamTech',
    category: 'Cameras',
    sku: 'CAM-UHD-03',
    stockQty: 15,
    weight: 0.8,
    thumbnail: 'https://images.unsplash.com/photo-1612198188060-c7c2a3b66eae?q=80&w=1200&auto=format&fit=crop',
    rating: 4.9,
    reviews: 489,
    isBestseller: true,
    isNew: false,
    isDealOfDay: true,
    isActive: true,
  },
  {
    id: 4,
    name: 'Portable Speaker',
    slug: 'portable-speaker',
    description: 'Compact wireless Bluetooth speaker delivering deep bass and 360-degree sound distribution.',
    price: 79.99,
    discount: 38.0,
    brand: 'AudioTech',
    category: 'Audio',
    sku: 'AUDIO-SPK-04',
    stockQty: 80,
    weight: 0.5,
    thumbnail: 'https://images.unsplash.com/photo-1589003077984-894e133814c9?q=80&w=1200&auto=format&fit=crop',
    rating: 4.5,
    reviews: 234,
    isBestseller: false,
    isNew: false,
    isDealOfDay: true,
    isActive: true,
  },
  {
    id: 5,
    name: 'Wireless Earbuds',
    slug: 'wireless-earbuds',
    description: 'Ergonomic, secure-fit in-ear headphones with touch controls and IPX7 sweat/water resistance.',
    price: 89.99,
    discount: 40.0,
    brand: 'AudioTech',
    category: 'Audio',
    sku: 'AUDIO-EAR-05',
    stockQty: 60,
    weight: 0.05,
    thumbnail: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?q=80&w=1200&auto=format&fit=crop',
    rating: 4.7,
    reviews: 567,
    isBestseller: true,
    isNew: true,
    isDealOfDay: true,
    isActive: true,
  },
  {
    id: 6,
    name: 'Phone Tripod',
    slug: 'phone-tripod',
    description: 'Extendable tripod stand with bluetooth remote control for stable photography and video recording.',
    price: 29.99,
    discount: 40.0,
    brand: 'AccessTech',
    category: 'Accessories',
    sku: 'ACC-TRIP-06',
    stockQty: 100,
    weight: 0.2,
    thumbnail: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?q=80&w=1200&auto=format&fit=crop',
    rating: 4.4,
    reviews: 123,
    isBestseller: false,
    isNew: false,
    isDealOfDay: true,
    isActive: true,
  },
  {
    id: 7,
    name: 'USB-C Hub',
    slug: 'usb-c-hub',
    description: '8-in-1 multi-port adapter with 4K HDMI, SD card reader, USB 3.0 ports, and Power Delivery passthrough.',
    price: 49.99,
    discount: 37.0,
    brand: 'AccessTech',
    category: 'Accessories',
    sku: 'ACC-HUB-07',
    stockQty: 120,
    weight: 0.1,
    thumbnail: 'https://images.unsplash.com/photo-1625948515291-69613efd103f?q=80&w=1200&auto=format&fit=crop',
    rating: 4.6,
    reviews: 345,
    isBestseller: false,
    isNew: true,
    isDealOfDay: true,
    isActive: true,
  },
  {
    id: 8,
    name: 'Phone Stand',
    slug: 'phone-stand',
    description: 'Adjustable, sturdy aluminum desktop phone cradle holder for video calls, reading, and watching movies.',
    price: 19.99,
    discount: 43.0,
    brand: 'AccessTech',
    category: 'Accessories',
    sku: 'ACC-STAND-08',
    stockQty: 200,
    weight: 0.15,
    thumbnail: 'https://images.unsplash.com/photo-1563394566578-f8fae67fa0fb?q=80&w=1200&auto=format&fit=crop',
    rating: 4.3,
    reviews: 89,
    isBestseller: false,
    isNew: false,
    isDealOfDay: true,
    isActive: true,
  },

  // Trending Deals (9 - 16)
  {
    id: 9,
    name: 'Mechanical Keyboard',
    slug: 'mechanical-keyboard',
    description: 'Tactile mechanical keyboard with customized RGB lighting effects and hot-swappable key switches.',
    price: 149.99,
    discount: 25.0,
    brand: 'KeyTech',
    category: 'Office & Desk',
    sku: 'OFF-KEY-09',
    stockQty: 40,
    weight: 1.0,
    thumbnail: 'https://images.unsplash.com/photo-1587829191301-dc798b83add3?q=80&w=1200&auto=format&fit=crop',
    rating: 4.8,
    reviews: 421,
    isBestseller: true,
    isNew: true,
    isTrending: true,
    isActive: true,
  },
  {
    id: 10,
    name: 'Gaming Mouse',
    slug: 'gaming-mouse',
    description: 'High-precision tracking mouse with adjustable DPI sensor and ergonomic grips for marathon gaming sessions.',
    price: 59.99,
    discount: 40.0,
    brand: 'KeyTech',
    category: 'Office & Desk',
    sku: 'OFF-MOUS-10',
    stockQty: 95,
    weight: 0.12,
    thumbnail: 'https://images.unsplash.com/photo-1527814050087-3793815479db?q=80&w=1200&auto=format&fit=crop',
    rating: 4.7,
    reviews: 312,
    isBestseller: false,
    isNew: false,
    isTrending: true,
    isActive: true,
  },
  {
    id: 11,
    name: 'Monitor Stand',
    slug: 'monitor-stand',
    description: 'Ergonomic wooden desk shelf and dual monitor stand riser with drawer compartments.',
    price: 89.99,
    discount: 36.0,
    brand: 'DeskTech',
    category: 'Office & Desk',
    sku: 'OFF-MON-11',
    stockQty: 25,
    weight: 2.5,
    thumbnail: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?q=80&w=1200&auto=format&fit=crop',
    rating: 4.5,
    reviews: 198,
    isBestseller: false,
    isNew: true,
    isTrending: true,
    isActive: true,
  },
  {
    id: 12,
    name: 'Desk Lamp',
    slug: 'desk-lamp',
    description: 'Dimmable smart LED desk light with wireless charging dock and adjustable arms.',
    price: 45.99,
    discount: 42.0,
    brand: 'DeskTech',
    category: 'Office & Desk',
    sku: 'OFF-LAMP-12',
    stockQty: 50,
    weight: 0.9,
    thumbnail: 'https://images.unsplash.com/photo-1565636192335-14c01e2335d6?q=80&w=1200&auto=format&fit=crop',
    rating: 4.6,
    reviews: 267,
    isBestseller: false,
    isNew: false,
    isTrending: true,
    isActive: true,
  },
  {
    id: 13,
    name: 'Phone Case',
    slug: 'phone-case',
    description: 'Shock-proof clear protective case with MagSafe compatibility and yellowing resistance.',
    price: 24.99,
    discount: 50.0,
    brand: 'CaseTech',
    category: 'Mobile Accessories',
    sku: 'ACC-CASE-13',
    stockQty: 150,
    weight: 0.03,
    thumbnail: 'https://images.unsplash.com/photo-1606933248051-5ce42bebce85?q=80&w=1200&auto=format&fit=crop',
    rating: 4.4,
    reviews: 534,
    isBestseller: true,
    isNew: false,
    isTrending: true,
    isActive: true,
  },
  {
    id: 14,
    name: 'Screen Protector',
    slug: 'screen-protector',
    description: 'Ultra-thin 9H hardness tempered glass shield with bubble-free installation frames.',
    price: 14.99,
    discount: 50.0,
    brand: 'CaseTech',
    category: 'Mobile Accessories',
    sku: 'ACC-PROT-14',
    stockQty: 300,
    weight: 0.01,
    thumbnail: 'https://images.unsplash.com/photo-1600163509057-ba94a3db4b18?q=80&w=1200&auto=format&fit=crop',
    rating: 4.5,
    reviews: 678,
    isBestseller: false,
    isNew: true,
    isTrending: true,
    isActive: true,
  },
  {
    id: 15,
    name: 'Cable Organizer',
    slug: 'cable-organizer',
    description: 'Silicone self-adhesive cable management holder clips for clean office workspaces.',
    price: 12.99,
    discount: 48.0,
    brand: 'DeskTech',
    category: 'Office & Desk',
    sku: 'OFF-ORG-15',
    stockQty: 180,
    weight: 0.05,
    thumbnail: 'https://images.unsplash.com/photo-1625948515291-69613efd103f?q=80&w=1200&auto=format&fit=crop',
    rating: 4.3,
    reviews: 145,
    isBestseller: false,
    isNew: false,
    isTrending: true,
    isActive: true,
  },
  {
    id: 16,
    name: 'Webcam',
    slug: 'webcam',
    description: '1080p full HD desktop camera with autofocus, dual noise-reducing stereo microphones.',
    price: 99.99,
    discount: 37.0,
    brand: 'CamTech',
    category: 'Cameras',
    sku: 'CAM-WEB-16',
    stockQty: 45,
    weight: 0.25,
    thumbnail: 'https://images.unsplash.com/photo-1587826922334-403e5d63b672?q=80&w=1200&auto=format&fit=crop',
    rating: 4.7,
    reviews: 289,
    isBestseller: true,
    isNew: true,
    isTrending: true,
    isActive: true,
  },
];

export const demoUsers = [
  {
    id: 1,
    email: 'customer@example.com',
    name: 'Alex Johnson',
    role: 'CUSTOMER',
    address: '742 Evergreen Terrace, Springfield, OR',
    phone: '+1 (555) 382-9104',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=300&auto=format&fit=crop',
  },
  {
    id: 2,
    email: 'admin@touchit.com',
    name: 'Sarah Connor',
    role: 'ADMIN',
    address: '100 Silicon Way, Tech City, CA',
    phone: '+1 (555) 902-1133',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=300&auto=format&fit=crop',
  },
];

export const initialOrders = [
  {
    orderId: 1001,
    userId: 1,
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    orderStatus: 'DELIVERED',
    paymentStatus: 'PAID',
    paymentMethod: 'Credit Card',
    shippingMethod: 'Express Delivery',
    shippingAddress: '742 Evergreen Terrace, Springfield, OR',
    subtotal: 129.99,
    discount: 0,
    tax: 6.5,
    shippingCost: 0,
    totalAmount: 136.49,
    orderItems: [
      {
        id: 1,
        productId: 1,
        quantity: 1,
        price: 129.99,
        discount: 25.0,
        total: 129.99,
        product: {
          id: 1,
          name: 'Premium Wireless Headphones',
          slug: 'premium-wireless-headphones',
          thumbnail: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=1200&auto=format&fit=crop',
        },
      },
    ],
  },
  {
    orderId: 1002,
    userId: 1,
    createdAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    orderStatus: 'PROCESSING',
    paymentStatus: 'PAID',
    paymentMethod: 'PayPal',
    shippingMethod: 'Standard Shipping',
    shippingAddress: '742 Evergreen Terrace, Springfield, OR',
    subtotal: 259.98,
    discount: 20.0,
    tax: 12.0,
    shippingCost: 0,
    totalAmount: 251.98,
    orderItems: [
      {
        id: 2,
        productId: 2,
        quantity: 1,
        price: 199.99,
        discount: 33.0,
        total: 199.99,
        product: {
          id: 2,
          name: 'Smart Watch Pro',
          slug: 'smart-watch-pro',
          thumbnail: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=1200&auto=format&fit=crop',
        },
      },
      {
        id: 3,
        productId: 10,
        quantity: 1,
        price: 59.99,
        discount: 40.0,
        total: 59.99,
        product: {
          id: 10,
          name: 'Gaming Mouse',
          slug: 'gaming-mouse',
          thumbnail: 'https://images.unsplash.com/photo-1527814050087-3793815479db?q=80&w=1200&auto=format&fit=crop',
        },
      },
    ],
  },
];
